export default [
  {
    name: "Cinema App",
    tools: "React | Firebase | Movie API",
    color: "#fcba03",
    id: "1",
    description:
      "This application is a Cinema App the lets the user explore the site and discover movies. For this project I used the movie database API to get all the movies' data. The insipration for this site is a combination of Netflix and HBO themes. Overall this was a fun project to build. The upcoming features are to add video trailers and authentication functionality",
    video: "9HkUCRxMGiA",
    backgroundPic: `/CinemaBackground.png`,
    thumbnail: `/cinema.png`,
    website: "https://cinema-app-eight.vercel.app/",
    github: "https://github.com/007Steve/Cinema-app",
    imageOne: "/Screen Shot 2020-12-11 at 2.34.39 PM.png",
    imageTwo: "/Screen Shot 2020-12-11 at 2.37.20 PM.png",
    imageThree: "/Screen Shot 2020-12-11 at 2.34.48 PM.png",
  },
  {
    name: "Twitter Clone",
    tools: "React | Firebase",
    color: "#03A3FF",
    id: "2",
    description:
      "The Twitter Clone App is a replica of Twitter that I created to challenge myself to see if I could build this particular layout. I used Firebase for the back-end and React for the front-end of this app.",
    backgroundPic: `/TwitterBackground.png`,
    thumbnail: `/twitter (1).png`,
    video: "nfECKR4MXqQ",
    website: "https://twitter-app-swart.vercel.app/",
    github: "https://github.com/007Steve/Twitter-App",
    imageOne: "/Screen Shot 2020-12-11 at 2.34.39 PM.png",
    imageTwo: "",
    imageThree: "",
  },
  {
    name: "Bolt Chat",
    tools: "React | Firebase | Redux",
    color: "#4FECD1",
    id: "3",
    description: "The Bolt Chat App is an instant messaging app that lets you communicate with others. I used Firebase for the back-end, Redux and React for the front-end of this app.",
    backgroundPic: `/bolt-chat-bg.png`,
    thumbnail: `/bolt chat.png`,
    video: "an8ZY-Rnw24",
    website: "https://chatapp-be4e6.firebaseapp.com/",
    github: "https://github.com/007Steve/Messaging-Project",
  },
  {
    name: "Quotes",
    tools: "HTML | CSS | Quotes API",
    color: "#1CD7BD",
    id: "4",
    description:
      "The quote generator is an app that generates random quotes. I am fetching data from the quote API and I also used CSS animation to give the quote the floating effect.",
    backgroundPic: `/QuoteBackground.png`,
    thumbnail: `/Copy of Copy of Untitled.png`,
    video: "0KeJrm1bSxI",
    website: "https://quotes-generator-nine.vercel.app/",
    github: "https://github.com/007Steve/Quotes-Generator",
    imageOne: "/Screen Shot 2020-12-12 at 12.56.02 AM.png",
    imageTwo: "",
    imageThree: "",
  },
  {
    name: "Peloton",
    tools: "React | CSS | Youtube API",
    color: "red",
    id: "5",
    description:
      "Peleton app is a clone of the Peloton website that provides you with the ability to check different workout videos. I'm using the Youtube API to pull in the videos for the app.",
    backgroundPic: `/PelotonBackground.png`,
    thumbnail: `/peloton.png`,
    video: "IUAYAI1G-Zk",
    website: "https://peloton-clone.vercel.app/",
    github: "https://github.com/007Steve/Peloton-clone",
    imageOne: "/Screen Shot 2020-12-11 at 3.22.18 PM.png",
    imageTwo: "",
    imageThree: "",
  },
];
